---
events:
  graz_monday_training_run:
    activ: true
    time: 0500
    location: somewhere
    day: Monday
  graz_thursday_morning_run:
    active: true
    time: 1500
    location: somewhere
    day: Thursday
